# Convert Angular Patternfly to SCSS
dependencies:
  patternfly-sass:
    git: https://github.com/hayesr/patternfly-sass.git

    # specify a local folder, contents will be moved under destination (next value)
    # path: ~/local/path/to/folder

    # destination for dependency is relative to conversion destination
    destination: vendor/patternfly-sass

pipelines:
  default:
    - replace_vars
    - replace_file_imports
    # - replace_mixin_definitions
    # - replace_mixins
    # - replace_spin
    # - replace_fade
    # - replace_image_urls
    # - remove_escaping
    # - convert_less_ampersand
    # - deinterpolate_vararg_mixins
    # - replace_calculation_semantics
    # - escape_variables_in_calc

import_overrides:
  # When we come across a given import path, replace it with a relative path from the destination directory
  "../node_modules/patternfly/dist/less/color-variables.less": ../vendor/patternfly-sass/assets/stylesheets/patternfly/_color-variables.scss
